# Database connection settings
database:
  host: "localhost"
  port: "3307"
  name: "minecraft_data"
  user: "root"
  password: ""
  # Maximum number of retry attempts for database operations
  maxRetryAttempts: 3
  # Delay between retry attempts in milliseconds
  retryDelayMs: 1000

# Debug mode - set to true to enable detailed logging
debug: false

# Save interval settings
saveInterval:
  # How often to save player data (in ticks, 20 ticks = 1 second)
  # Default: 1200 ticks (1 minute)
  ticks: 1200
  # Percentage of online players to save in each batch
  # Default: 20% (saves all players over 5 batches)
  batchSizePercent: 20

# Player statistics saving settings
statsInterval:
  # How often to save player statistics (in ticks, 20 ticks = 1 second)
  ticks: 6000  # 5 minutes

# Death statistics settings
deathStats:
  # Whether to count deaths caused by the /suicide command
  # Set to false to not count suicide command deaths in player statistics
  countSuicideCommandDeaths: false
